// *************************************************************************
//
// Copyright 2022 Xilinx, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// *************************************************************************
`timescale 1ns/1ps

module rdma_subsystem #(
  parameter  C_AXIS_DATA_WIDTH = 512,
  parameter  C_AXIS_KEEP_WIDTH = 64,
  parameter C_AXIS_IMMDT_WIDTH = 64
) (
  // AXIL interface for RDMA control register
  input  [31:0] s_axil_awaddr,
  input         s_axil_awvalid,
  output        s_axil_awready,
  input  [31:0] s_axil_wdata,
  input   [3:0] s_axil_wstrb,
  input         s_axil_wvalid,
  output        s_axil_wready,
  input  [31:0] s_axil_araddr,
  input         s_axil_arvalid,
  output        s_axil_arready,
  output [31:0] s_axil_rdata,
  output        s_axil_rvalid,
  output  [1:0] s_axil_rresp,
  input         s_axil_rready,
  output  [1:0] s_axil_bresp,
  output        s_axil_bvalid,
  input         s_axil_bready,

  // RDMA TX interface (including roce and non-roce packets) to CMAC TX path
  output [C_AXIS_DATA_WIDTH-1:0] m_rdma2cmac_axis_tdata,
  output [C_AXIS_KEEP_WIDTH-1:0] m_rdma2cmac_axis_tkeep,
  output                         m_rdma2cmac_axis_tvalid,
  output                         m_rdma2cmac_axis_tlast,
  input                          m_rdma2cmac_axis_tready,

  // Non-RDMA packets from QDMA TX bypassing RDMA TX
  input  [C_AXIS_DATA_WIDTH-1:0] s_qdma2rdma_non_roce_axis_tdata,
  input  [C_AXIS_KEEP_WIDTH-1:0] s_qdma2rdma_non_roce_axis_tkeep,
  input                          s_qdma2rdma_non_roce_axis_tvalid,
  input                          s_qdma2rdma_non_roce_axis_tlast,
  output                         s_qdma2rdma_non_roce_axis_tready,

  // RDMA RX interface from CMAC RX, no rx backpressure
  input  [C_AXIS_DATA_WIDTH-1:0] s_cmac2rdma_roce_axis_tdata,
  input  [C_AXIS_KEEP_WIDTH-1:0] s_cmac2rdma_roce_axis_tkeep,
  input                          s_cmac2rdma_roce_axis_tvalid,
  input                          s_cmac2rdma_roce_axis_tlast,
  input                          s_cmac2rdma_roce_axis_tuser,

  // Non-RDMA packets from CMAC RX bypassing RDMA, no rx backpressure
  input  [C_AXIS_DATA_WIDTH-1:0] s_cmac2rdma_non_roce_axis_tdata,
  input  [C_AXIS_KEEP_WIDTH-1:0] s_cmac2rdma_non_roce_axis_tkeep,
  input                          s_cmac2rdma_non_roce_axis_tvalid,
  input                          s_cmac2rdma_non_roce_axis_tlast,
  input                          s_cmac2rdma_non_roce_axis_tuser,

  // Non-RDMA packets bypassing RDMA to QDMA RX
  output [C_AXIS_DATA_WIDTH-1:0] m_rdma2qdma_non_roce_axis_tdata,
  output [C_AXIS_KEEP_WIDTH-1:0] m_rdma2qdma_non_roce_axis_tkeep,
  output                         m_rdma2qdma_non_roce_axis_tvalid,
  output                         m_rdma2qdma_non_roce_axis_tlast,
  input                          m_rdma2qdma_non_roce_axis_tready,

  // invalidate or immediate data from roce IETH/IMMDT header
  output [C_AXIS_IMMDT_WIDTH-1:0] m_rdma2user_ieth_immdt_axis_tdata,
  output                          m_rdma2user_ieth_immdt_axis_tlast,
  output                          m_rdma2user_ieth_immdt_axis_tvalid,
  input                           m_rdma2user_ieth_immdt_axis_trdy,

  // RDMA AXI MM interface used to store payload from RDMA MAD, Send or Write operation
  output           m_axi_rdma_send_write_payload_store_awid,
  output  [63 : 0] m_axi_rdma_send_write_payload_store_awaddr,
  output  [31 : 0] m_axi_rdma_send_write_payload_store_awuser,
  output   [7 : 0] m_axi_rdma_send_write_payload_store_awlen,
  output   [2 : 0] m_axi_rdma_send_write_payload_store_awsize,
  output   [1 : 0] m_axi_rdma_send_write_payload_store_awburst,
  output   [3 : 0] m_axi_rdma_send_write_payload_store_awcache,
  output   [2 : 0] m_axi_rdma_send_write_payload_store_awprot,
  output           m_axi_rdma_send_write_payload_store_awvalid,
  input            m_axi_rdma_send_write_payload_store_awready,
  output [511 : 0] m_axi_rdma_send_write_payload_store_wdata,
  output  [63 : 0] m_axi_rdma_send_write_payload_store_wstrb,
  output           m_axi_rdma_send_write_payload_store_wlast,
  output           m_axi_rdma_send_write_payload_store_wvalid,
  input            m_axi_rdma_send_write_payload_store_wready,
  output           m_axi_rdma_send_write_payload_store_awlock,
  input            m_axi_rdma_send_write_payload_store_bid,
  input    [1 : 0] m_axi_rdma_send_write_payload_store_bresp,
  input            m_axi_rdma_send_write_payload_store_bvalid,
  output           m_axi_rdma_send_write_payload_store_bready,
  output           m_axi_rdma_send_write_payload_store_arid,
  output  [63 : 0] m_axi_rdma_send_write_payload_store_araddr,
  output   [7 : 0] m_axi_rdma_send_write_payload_store_arlen,
  output   [2 : 0] m_axi_rdma_send_write_payload_store_arsize,
  output   [1 : 0] m_axi_rdma_send_write_payload_store_arburst,
  output   [3 : 0] m_axi_rdma_send_write_payload_store_arcache,
  output   [2 : 0] m_axi_rdma_send_write_payload_store_arprot,
  output           m_axi_rdma_send_write_payload_store_arvalid,
  input            m_axi_rdma_send_write_payload_store_arready,
  input            m_axi_rdma_send_write_payload_store_rid,
  input  [511 : 0] m_axi_rdma_send_write_payload_store_rdata,
  input    [1 : 0] m_axi_rdma_send_write_payload_store_rresp,
  input            m_axi_rdma_send_write_payload_store_rlast,
  input            m_axi_rdma_send_write_payload_store_rvalid,
  output           m_axi_rdma_send_write_payload_store_rready,
  output           m_axi_rdma_send_write_payload_store_arlock,

  // RDMA AXI MM interface used to store payload from RDMA Read response operation
  output           m_axi_rdma_rsp_payload_awid,
  output  [63 : 0] m_axi_rdma_rsp_payload_awaddr,
  output   [7 : 0] m_axi_rdma_rsp_payload_awlen,
  output   [2 : 0] m_axi_rdma_rsp_payload_awsize,
  output   [1 : 0] m_axi_rdma_rsp_payload_awburst,
  output   [3 : 0] m_axi_rdma_rsp_payload_awcache,
  output   [2 : 0] m_axi_rdma_rsp_payload_awprot,
  output           m_axi_rdma_rsp_payload_awvalid,
  input            m_axi_rdma_rsp_payload_awready,
  output [511 : 0] m_axi_rdma_rsp_payload_wdata,
  output  [63 : 0] m_axi_rdma_rsp_payload_wstrb,
  output           m_axi_rdma_rsp_payload_wlast,
  output           m_axi_rdma_rsp_payload_wvalid,
  input            m_axi_rdma_rsp_payload_wready,
  output           m_axi_rdma_rsp_payload_awlock,
  input            m_axi_rdma_rsp_payload_bid,
  input    [1 : 0] m_axi_rdma_rsp_payload_bresp,
  input            m_axi_rdma_rsp_payload_bvalid,
  output           m_axi_rdma_rsp_payload_bready,
  output           m_axi_rdma_rsp_payload_arid,
  output  [63 : 0] m_axi_rdma_rsp_payload_araddr,
  output   [7 : 0] m_axi_rdma_rsp_payload_arlen,
  output   [2 : 0] m_axi_rdma_rsp_payload_arsize,
  output   [1 : 0] m_axi_rdma_rsp_payload_arburst,
  output   [3 : 0] m_axi_rdma_rsp_payload_arcache,
  output   [2 : 0] m_axi_rdma_rsp_payload_arprot,
  output           m_axi_rdma_rsp_payload_arvalid,
  input            m_axi_rdma_rsp_payload_arready,
  input            m_axi_rdma_rsp_payload_rid,
  input  [511 : 0] m_axi_rdma_rsp_payload_rdata,
  input    [1 : 0] m_axi_rdma_rsp_payload_rresp,
  input            m_axi_rdma_rsp_payload_rlast,
  input            m_axi_rdma_rsp_payload_rvalid,
  output           m_axi_rdma_rsp_payload_rready,
  output           m_axi_rdma_rsp_payload_arlock,

  // RDMA AXI MM interface used to fetch WQE entries in the senq queue from DDR by the QP manager
  output           m_axi_qp_get_wqe_awid,
  output  [63 : 0] m_axi_qp_get_wqe_awaddr,
  output   [7 : 0] m_axi_qp_get_wqe_awlen,
  output   [2 : 0] m_axi_qp_get_wqe_awsize,
  output   [1 : 0] m_axi_qp_get_wqe_awburst,
  output   [3 : 0] m_axi_qp_get_wqe_awcache,
  output   [2 : 0] m_axi_qp_get_wqe_awprot,
  output           m_axi_qp_get_wqe_awvalid,
  input            m_axi_qp_get_wqe_awready,
  output [511 : 0] m_axi_qp_get_wqe_wdata,
  output  [63 : 0] m_axi_qp_get_wqe_wstrb,
  output           m_axi_qp_get_wqe_wlast,
  output           m_axi_qp_get_wqe_wvalid,
  input            m_axi_qp_get_wqe_wready,
  output           m_axi_qp_get_wqe_awlock,
  input            m_axi_qp_get_wqe_bid,
  input    [1 : 0] m_axi_qp_get_wqe_bresp,
  input            m_axi_qp_get_wqe_bvalid,
  output           m_axi_qp_get_wqe_bready,
  output           m_axi_qp_get_wqe_arid,
  output  [63 : 0] m_axi_qp_get_wqe_araddr,
  output   [7 : 0] m_axi_qp_get_wqe_arlen,
  output   [2 : 0] m_axi_qp_get_wqe_arsize,
  output   [1 : 0] m_axi_qp_get_wqe_arburst,
  output   [3 : 0] m_axi_qp_get_wqe_arcache,
  output   [2 : 0] m_axi_qp_get_wqe_arprot,
  output           m_axi_qp_get_wqe_arvalid,
  input            m_axi_qp_get_wqe_arready,
  input            m_axi_qp_get_wqe_rid,
  input  [511 : 0] m_axi_qp_get_wqe_rdata,
  input    [1 : 0] m_axi_qp_get_wqe_rresp,
  input            m_axi_qp_get_wqe_rlast,
  input            m_axi_qp_get_wqe_rvalid,
  output           m_axi_qp_get_wqe_rready,
  output           m_axi_qp_get_wqe_arlock,

  // RDMA AXI MM interface used to store payload of an outgoing RDMA write packet to a retry buffer
  output           m_axi_payload_to_retry_buf_awid,
  output  [63 : 0] m_axi_payload_to_retry_buf_awaddr,
  output   [7 : 0] m_axi_payload_to_retry_buf_awlen,
  output   [2 : 0] m_axi_payload_to_retry_buf_awsize,
  output   [1 : 0] m_axi_payload_to_retry_buf_awburst,
  output   [3 : 0] m_axi_payload_to_retry_buf_awcache,
  output   [2 : 0] m_axi_payload_to_retry_buf_awprot,
  output           m_axi_payload_to_retry_buf_awvalid,
  input            m_axi_payload_to_retry_buf_awready,
  output [511 : 0] m_axi_payload_to_retry_buf_wdata,
  output  [63 : 0] m_axi_payload_to_retry_buf_wstrb,
  output           m_axi_payload_to_retry_buf_wlast,
  output           m_axi_payload_to_retry_buf_wvalid,
  input            m_axi_payload_to_retry_buf_wready,
  output           m_axi_payload_to_retry_buf_awlock,
  input            m_axi_payload_to_retry_buf_bid,
  input    [1 : 0] m_axi_payload_to_retry_buf_bresp,
  input            m_axi_payload_to_retry_buf_bvalid,
  output           m_axi_payload_to_retry_buf_bready,
  output           m_axi_payload_to_retry_buf_arid,
  output  [63 : 0] m_axi_payload_to_retry_buf_araddr,
  output   [7 : 0] m_axi_payload_to_retry_buf_arlen,
  output   [2 : 0] m_axi_payload_to_retry_buf_arsize,
  output   [1 : 0] m_axi_payload_to_retry_buf_arburst,
  output   [3 : 0] m_axi_payload_to_retry_buf_arcache,
  output   [2 : 0] m_axi_payload_to_retry_buf_arprot,
  output           m_axi_payload_to_retry_buf_arvalid,
  input            m_axi_payload_to_retry_buf_arready,
  input            m_axi_payload_to_retry_buf_rid,
  input  [511 : 0] m_axi_payload_to_retry_buf_rdata,
  input    [1 : 0] m_axi_payload_to_retry_buf_rresp,
  input            m_axi_payload_to_retry_buf_rlast,
  input            m_axi_payload_to_retry_buf_rvalid,
  output           m_axi_payload_to_retry_buf_rready,
  output           m_axi_payload_to_retry_buf_arlock,

  // RDMA AXI MM interface used to get payload of an outgoing RDMA send/write and read response packets
  output           m_axi_pktgen_get_payload_awid,
  output  [63 : 0] m_axi_pktgen_get_payload_awaddr,
  output   [7 : 0] m_axi_pktgen_get_payload_awlen,
  output   [2 : 0] m_axi_pktgen_get_payload_awsize,
  output   [1 : 0] m_axi_pktgen_get_payload_awburst,
  output   [3 : 0] m_axi_pktgen_get_payload_awcache,
  output   [2 : 0] m_axi_pktgen_get_payload_awprot,
  output           m_axi_pktgen_get_payload_awvalid,
  input            m_axi_pktgen_get_payload_awready,
  output [511 : 0] m_axi_pktgen_get_payload_wdata,
  output  [63 : 0] m_axi_pktgen_get_payload_wstrb,
  output           m_axi_pktgen_get_payload_wlast,
  output           m_axi_pktgen_get_payload_wvalid,
  input            m_axi_pktgen_get_payload_wready,
  output           m_axi_pktgen_get_payload_awlock,
  input            m_axi_pktgen_get_payload_bid,
  input    [1 : 0] m_axi_pktgen_get_payload_bresp,
  input            m_axi_pktgen_get_payload_bvalid,
  output           m_axi_pktgen_get_payload_bready,
  output           m_axi_pktgen_get_payload_arid,
  output  [63 : 0] m_axi_pktgen_get_payload_araddr,
  output   [7 : 0] m_axi_pktgen_get_payload_arlen,
  output   [2 : 0] m_axi_pktgen_get_payload_arsize,
  output   [1 : 0] m_axi_pktgen_get_payload_arburst,
  output   [3 : 0] m_axi_pktgen_get_payload_arcache,
  output   [2 : 0] m_axi_pktgen_get_payload_arprot,
  output           m_axi_pktgen_get_payload_arvalid,
  input            m_axi_pktgen_get_payload_arready,
  input            m_axi_pktgen_get_payload_rid,
  input  [511 : 0] m_axi_pktgen_get_payload_rdata,
  input    [1 : 0] m_axi_pktgen_get_payload_rresp,
  input            m_axi_pktgen_get_payload_rlast,
  input            m_axi_pktgen_get_payload_rvalid,
  output           m_axi_pktgen_get_payload_rready,
  output           m_axi_pktgen_get_payload_arlock,

  // RDMA AXI MM interface used to write completion entries to a completion queue in the DDR
  output           m_axi_write_completion_awid,
  output  [63 : 0] m_axi_write_completion_awaddr,
  output   [7 : 0] m_axi_write_completion_awlen,
  output   [2 : 0] m_axi_write_completion_awsize,
  output   [1 : 0] m_axi_write_completion_awburst,
  output   [3 : 0] m_axi_write_completion_awcache,
  output   [2 : 0] m_axi_write_completion_awprot,
  output           m_axi_write_completion_awvalid,
  input            m_axi_write_completion_awready,
  output [511 : 0] m_axi_write_completion_wdata,
  output  [63 : 0] m_axi_write_completion_wstrb,
  output           m_axi_write_completion_wlast,
  output           m_axi_write_completion_wvalid,
  input            m_axi_write_completion_wready,
  output           m_axi_write_completion_awlock,
  input            m_axi_write_completion_bid,
  input    [1 : 0] m_axi_write_completion_bresp,
  input            m_axi_write_completion_bvalid,
  output           m_axi_write_completion_bready,
  output           m_axi_write_completion_arid,
  output  [63 : 0] m_axi_write_completion_araddr,
  output   [7 : 0] m_axi_write_completion_arlen,
  output   [2 : 0] m_axi_write_completion_arsize,
  output   [1 : 0] m_axi_write_completion_arburst,
  output   [3 : 0] m_axi_write_completion_arcache,
  output   [2 : 0] m_axi_write_completion_arprot,
  output           m_axi_write_completion_arvalid,
  input            m_axi_write_completion_arready,
  input            m_axi_write_completion_rid,
  input  [511 : 0] m_axi_write_completion_rdata,
  input    [1 : 0] m_axi_write_completion_rresp,
  input            m_axi_write_completion_rlast,
  input            m_axi_write_completion_rvalid,
  output           m_axi_write_completion_rready,
  output           m_axi_write_completion_arlock,

  // Send WQE completion queue doorbell
  output           resp_hndler_o_send_cq_db_cnt_valid,
  output     [9:0] resp_hndler_o_send_cq_db_addr,
  output    [31:0] resp_hndler_o_send_cq_db_cnt,
  input            resp_hndler_i_send_cq_db_rdy,

  // Send WQE producer index doorbell
  input     [15:0] i_qp_sq_pidb_hndshk,
  input     [31:0] i_qp_sq_pidb_wr_addr_hndshk,
  input            i_qp_sq_pidb_wr_valid_hndshk,
  output           o_qp_sq_pidb_wr_rdy,

  // RDMA-Send consumer index doorbell
  input     [15:0] i_qp_rq_cidb_hndshk,
  input     [31:0] i_qp_rq_cidb_wr_addr_hndshk,
  input            i_qp_rq_cidb_wr_valid_hndshk,
  output           o_qp_rq_cidb_wr_rdy,

  // RDMA-Send producer index doorbell
  output    [31:0] rx_pkt_hndler_o_rq_db_data,
  output     [9:0] rx_pkt_hndler_o_rq_db_addr,
  output           rx_pkt_hndler_o_rq_db_data_valid,
  input            rx_pkt_hndler_i_rq_db_rdy,

  output           rnic_intr,
  input      [8:0] stat_rx_pause_req,
  output     [8:0] ctl_tx_pause_req,
  output           ctl_tx_resend_pause,

  output           o_global_dbg_cnt_en,
  output           o_global_dbg_cnt_clr,

  input  axil_rstn,
  input  axis_rstn,
  input  axil_clk,
  input  axis_clk,
  output rdma_resetn_done
);

rdma_core rdma_inst (
  .s_axi_lite_aclk                   (axil_clk),
  .s_axi_lite_aresetn                (axil_rstn),
  .m_axi_aclk                        (axis_clk),
  .m_axi_aresetn                     (axis_rstn),
  .cmac_rx_clk                       (axis_clk),
  .cmac_rx_rst                       (~axis_rstn),
  .cmac_tx_clk                       (axis_clk),
  .cmac_tx_rst                       (~axis_rstn),
  .system_resetn                     (rdma_resetn_done),

  .s_axi_lite_awaddr                 (s_axil_awaddr),
  .s_axi_lite_awready                (s_axil_awready),
  .s_axi_lite_awvalid                (s_axil_awvalid),
  .s_axi_lite_araddr                 (s_axil_araddr),
  .s_axi_lite_arready                (s_axil_arready),
  .s_axi_lite_arvalid                (s_axil_arvalid),
  .s_axi_lite_wdata                  (s_axil_wdata),
  .s_axi_lite_wstrb                  (s_axil_wstrb),
  .s_axi_lite_wready                 (s_axil_wready),
  .s_axi_lite_wvalid                 (s_axil_wvalid),
  .s_axi_lite_rdata                  (s_axil_rdata),
  .s_axi_lite_rresp                  (s_axil_rresp),
  .s_axi_lite_rready                 (s_axil_rready),
  .s_axi_lite_rvalid                 (s_axil_rvalid),
  .s_axi_lite_bresp                  (s_axil_bresp),
  .s_axi_lite_bready                 (s_axil_bready),
  .s_axi_lite_bvalid                 (s_axil_bvalid),

  // RDMA AXI MM interface used to store payload from RDMA MAD, Send or Write operation
  .rx_pkt_hndler_ddr_m_axi_awid      (m_axi_rdma_send_write_payload_store_awid),
  .rx_pkt_hndler_ddr_m_axi_awaddr    (m_axi_rdma_send_write_payload_store_awaddr),
  .rx_pkt_hndler_ddr_m_axi_awuser    (m_axi_rdma_send_write_payload_store_awuser),
  .rx_pkt_hndler_ddr_m_axi_awlen     (m_axi_rdma_send_write_payload_store_awlen),
  .rx_pkt_hndler_ddr_m_axi_awsize    (m_axi_rdma_send_write_payload_store_awsize),
  .rx_pkt_hndler_ddr_m_axi_awburst   (m_axi_rdma_send_write_payload_store_awburst),
  .rx_pkt_hndler_ddr_m_axi_awcache   (m_axi_rdma_send_write_payload_store_awcache),
  .rx_pkt_hndler_ddr_m_axi_awprot    (m_axi_rdma_send_write_payload_store_awprot),
  .rx_pkt_hndler_ddr_m_axi_awvalid   (m_axi_rdma_send_write_payload_store_awvalid),
  .rx_pkt_hndler_ddr_m_axi_awready   (m_axi_rdma_send_write_payload_store_awready),
  .rx_pkt_hndler_ddr_m_axi_wdata     (m_axi_rdma_send_write_payload_store_wdata),
  .rx_pkt_hndler_ddr_m_axi_wstrb     (m_axi_rdma_send_write_payload_store_wstrb),
  .rx_pkt_hndler_ddr_m_axi_wlast     (m_axi_rdma_send_write_payload_store_wlast),
  .rx_pkt_hndler_ddr_m_axi_wvalid    (m_axi_rdma_send_write_payload_store_wvalid),
  .rx_pkt_hndler_ddr_m_axi_wready    (m_axi_rdma_send_write_payload_store_wready),
  .rx_pkt_hndler_ddr_m_axi_awlock    (m_axi_rdma_send_write_payload_store_awlock),
  .rx_pkt_hndler_ddr_m_axi_bid       (m_axi_rdma_send_write_payload_store_bid),
  .rx_pkt_hndler_ddr_m_axi_bresp     (m_axi_rdma_send_write_payload_store_bresp),
  .rx_pkt_hndler_ddr_m_axi_bvalid    (m_axi_rdma_send_write_payload_store_bvalid),
  .rx_pkt_hndler_ddr_m_axi_bready    (m_axi_rdma_send_write_payload_store_bready),
  .rx_pkt_hndler_ddr_m_axi_arid      (m_axi_rdma_send_write_payload_store_arid),
  .rx_pkt_hndler_ddr_m_axi_araddr    (m_axi_rdma_send_write_payload_store_araddr),
  .rx_pkt_hndler_ddr_m_axi_arlen     (m_axi_rdma_send_write_payload_store_arlen),
  .rx_pkt_hndler_ddr_m_axi_arsize    (m_axi_rdma_send_write_payload_store_arsize),
  .rx_pkt_hndler_ddr_m_axi_arburst   (m_axi_rdma_send_write_payload_store_arburst),
  .rx_pkt_hndler_ddr_m_axi_arcache   (m_axi_rdma_send_write_payload_store_arcache),
  .rx_pkt_hndler_ddr_m_axi_arprot    (m_axi_rdma_send_write_payload_store_arprot),
  .rx_pkt_hndler_ddr_m_axi_arvalid   (m_axi_rdma_send_write_payload_store_arvalid),
  .rx_pkt_hndler_ddr_m_axi_arready   (m_axi_rdma_send_write_payload_store_arready),
  .rx_pkt_hndler_ddr_m_axi_rid       (m_axi_rdma_send_write_payload_store_rid),
  .rx_pkt_hndler_ddr_m_axi_rdata     (m_axi_rdma_send_write_payload_store_rdata),
  .rx_pkt_hndler_ddr_m_axi_rresp     (m_axi_rdma_send_write_payload_store_rresp),
  .rx_pkt_hndler_ddr_m_axi_rlast     (m_axi_rdma_send_write_payload_store_rlast),
  .rx_pkt_hndler_ddr_m_axi_rvalid    (m_axi_rdma_send_write_payload_store_rvalid),
  .rx_pkt_hndler_ddr_m_axi_rready    (m_axi_rdma_send_write_payload_store_rready),
  .rx_pkt_hndler_ddr_m_axi_arlock    (m_axi_rdma_send_write_payload_store_arlock),

  // RDMA AXI MM interface used to store payload from RDMA Read response operation
  .rx_pkt_hndler_rdrsp_m_axi_awid    (m_axi_rdma_rsp_payload_awid),
  .rx_pkt_hndler_rdrsp_m_axi_awaddr  (m_axi_rdma_rsp_payload_awaddr),
  .rx_pkt_hndler_rdrsp_m_axi_awlen   (m_axi_rdma_rsp_payload_awlen),
  .rx_pkt_hndler_rdrsp_m_axi_awsize  (m_axi_rdma_rsp_payload_awsize),
  .rx_pkt_hndler_rdrsp_m_axi_awburst (m_axi_rdma_rsp_payload_awburst),
  .rx_pkt_hndler_rdrsp_m_axi_awcache (m_axi_rdma_rsp_payload_awcache),
  .rx_pkt_hndler_rdrsp_m_axi_awprot  (m_axi_rdma_rsp_payload_awprot),
  .rx_pkt_hndler_rdrsp_m_axi_awvalid (m_axi_rdma_rsp_payload_awvalid),
  .rx_pkt_hndler_rdrsp_m_axi_awready (m_axi_rdma_rsp_payload_awready),
  .rx_pkt_hndler_rdrsp_m_axi_wdata   (m_axi_rdma_rsp_payload_wdata),
  .rx_pkt_hndler_rdrsp_m_axi_wstrb   (m_axi_rdma_rsp_payload_wstrb),
  .rx_pkt_hndler_rdrsp_m_axi_wlast   (m_axi_rdma_rsp_payload_wlast),
  .rx_pkt_hndler_rdrsp_m_axi_wvalid  (m_axi_rdma_rsp_payload_wvalid),
  .rx_pkt_hndler_rdrsp_m_axi_wready  (m_axi_rdma_rsp_payload_wready),
  .rx_pkt_hndler_rdrsp_m_axi_awlock  (m_axi_rdma_rsp_payload_awlock),
  .rx_pkt_hndler_rdrsp_m_axi_bid     (m_axi_rdma_rsp_payload_bid),
  .rx_pkt_hndler_rdrsp_m_axi_bresp   (m_axi_rdma_rsp_payload_bresp),
  .rx_pkt_hndler_rdrsp_m_axi_bvalid  (m_axi_rdma_rsp_payload_bvalid),
  .rx_pkt_hndler_rdrsp_m_axi_bready  (m_axi_rdma_rsp_payload_bready),
  .rx_pkt_hndler_rdrsp_m_axi_arid    (m_axi_rdma_rsp_payload_arid),
  .rx_pkt_hndler_rdrsp_m_axi_araddr  (m_axi_rdma_rsp_payload_araddr),
  .rx_pkt_hndler_rdrsp_m_axi_arlen   (m_axi_rdma_rsp_payload_arlen),
  .rx_pkt_hndler_rdrsp_m_axi_arsize  (m_axi_rdma_rsp_payload_arsize),
  .rx_pkt_hndler_rdrsp_m_axi_arburst (m_axi_rdma_rsp_payload_arburst),
  .rx_pkt_hndler_rdrsp_m_axi_arcache (m_axi_rdma_rsp_payload_arcache),
  .rx_pkt_hndler_rdrsp_m_axi_arprot  (m_axi_rdma_rsp_payload_arprot),
  .rx_pkt_hndler_rdrsp_m_axi_arvalid (m_axi_rdma_rsp_payload_arvalid),
  .rx_pkt_hndler_rdrsp_m_axi_arready (m_axi_rdma_rsp_payload_arready),
  .rx_pkt_hndler_rdrsp_m_axi_rid     (m_axi_rdma_rsp_payload_rid),
  .rx_pkt_hndler_rdrsp_m_axi_rdata   (m_axi_rdma_rsp_payload_rdata),
  .rx_pkt_hndler_rdrsp_m_axi_rresp   (m_axi_rdma_rsp_payload_rresp),
  .rx_pkt_hndler_rdrsp_m_axi_rlast   (m_axi_rdma_rsp_payload_rlast),
  .rx_pkt_hndler_rdrsp_m_axi_rvalid  (m_axi_rdma_rsp_payload_rvalid),
  .rx_pkt_hndler_rdrsp_m_axi_rready  (m_axi_rdma_rsp_payload_rready),
  .rx_pkt_hndler_rdrsp_m_axi_arlock  (m_axi_rdma_rsp_payload_arlock),

  // RDMA AXI MM interface used to fetch WQE entries in the send queue from DDR by the QP manage
  .qp_mgr_m_axi_awid                 (m_axi_qp_get_wqe_awid),
  .qp_mgr_m_axi_awaddr               (m_axi_qp_get_wqe_awaddr),
  .qp_mgr_m_axi_awlen                (m_axi_qp_get_wqe_awlen),
  .qp_mgr_m_axi_awsize               (m_axi_qp_get_wqe_awsize),
  .qp_mgr_m_axi_awburst              (m_axi_qp_get_wqe_awburst),
  .qp_mgr_m_axi_awcache              (m_axi_qp_get_wqe_awcache),
  .qp_mgr_m_axi_awprot               (m_axi_qp_get_wqe_awprot),
  .qp_mgr_m_axi_awvalid              (m_axi_qp_get_wqe_awvalid),
  .qp_mgr_m_axi_awready              (m_axi_qp_get_wqe_awready),
  .qp_mgr_m_axi_wdata                (m_axi_qp_get_wqe_wdata),
  .qp_mgr_m_axi_wstrb                (m_axi_qp_get_wqe_wstrb),
  .qp_mgr_m_axi_wlast                (m_axi_qp_get_wqe_wlast),
  .qp_mgr_m_axi_wvalid               (m_axi_qp_get_wqe_wvalid),
  .qp_mgr_m_axi_wready               (m_axi_qp_get_wqe_wready),
  .qp_mgr_m_axi_awlock               (m_axi_qp_get_wqe_awlock),
  .qp_mgr_m_axi_bid                  (m_axi_qp_get_wqe_bid),
  .qp_mgr_m_axi_bresp                (m_axi_qp_get_wqe_bresp),
  .qp_mgr_m_axi_bvalid               (m_axi_qp_get_wqe_bvalid),
  .qp_mgr_m_axi_bready               (m_axi_qp_get_wqe_bready),
  .qp_mgr_m_axi_arid                 (m_axi_qp_get_wqe_arid),
  .qp_mgr_m_axi_araddr               (m_axi_qp_get_wqe_araddr),
  .qp_mgr_m_axi_arlen                (m_axi_qp_get_wqe_arlen),
  .qp_mgr_m_axi_arsize               (m_axi_qp_get_wqe_arsize),
  .qp_mgr_m_axi_arburst              (m_axi_qp_get_wqe_arburst),
  .qp_mgr_m_axi_arcache              (m_axi_qp_get_wqe_arcache),
  .qp_mgr_m_axi_arprot               (m_axi_qp_get_wqe_arprot),
  .qp_mgr_m_axi_arvalid              (m_axi_qp_get_wqe_arvalid),
  .qp_mgr_m_axi_arready              (m_axi_qp_get_wqe_arready),
  .qp_mgr_m_axi_rid                  (m_axi_qp_get_wqe_rid),
  .qp_mgr_m_axi_rdata                (m_axi_qp_get_wqe_rdata),
  .qp_mgr_m_axi_rresp                (m_axi_qp_get_wqe_rresp),
  .qp_mgr_m_axi_rlast                (m_axi_qp_get_wqe_rlast),
  .qp_mgr_m_axi_rvalid               (m_axi_qp_get_wqe_rvalid),
  .qp_mgr_m_axi_rready               (m_axi_qp_get_wqe_rready),
  .qp_mgr_m_axi_arlock               (m_axi_qp_get_wqe_arlock),

  // RDMA TX interface to CMAC TX path in AXIS format
  .cmac_m_axis_tdata                 (m_rdma2cmac_axis_tdata),
  .cmac_m_axis_tkeep                 (m_rdma2cmac_axis_tkeep),
  .cmac_m_axis_tvalid                (m_rdma2cmac_axis_tvalid),
  .cmac_m_axis_tlast                 (m_rdma2cmac_axis_tlast),
  .cmac_m_axis_tready                (m_rdma2cmac_axis_tready),

  // store payload of an outgoing RDMA write packet to a retry buffer
  .wqe_proc_wr_ddr_m_axi_awid        (m_axi_payload_to_retry_buf_awid),
  .wqe_proc_wr_ddr_m_axi_awaddr      (m_axi_payload_to_retry_buf_awaddr),
  .wqe_proc_wr_ddr_m_axi_awlen       (m_axi_payload_to_retry_buf_awlen),
  .wqe_proc_wr_ddr_m_axi_awsize      (m_axi_payload_to_retry_buf_awsize),
  .wqe_proc_wr_ddr_m_axi_awburst     (m_axi_payload_to_retry_buf_awburst),
  .wqe_proc_wr_ddr_m_axi_awcache     (m_axi_payload_to_retry_buf_awcache),
  .wqe_proc_wr_ddr_m_axi_awprot      (m_axi_payload_to_retry_buf_awprot),
  .wqe_proc_wr_ddr_m_axi_awvalid     (m_axi_payload_to_retry_buf_awvalid),
  .wqe_proc_wr_ddr_m_axi_awready     (m_axi_payload_to_retry_buf_awready),
  .wqe_proc_wr_ddr_m_axi_wdata       (m_axi_payload_to_retry_buf_wdata),
  .wqe_proc_wr_ddr_m_axi_wstrb       (m_axi_payload_to_retry_buf_wstrb),
  .wqe_proc_wr_ddr_m_axi_wlast       (m_axi_payload_to_retry_buf_wlast),
  .wqe_proc_wr_ddr_m_axi_wvalid      (m_axi_payload_to_retry_buf_wvalid),
  .wqe_proc_wr_ddr_m_axi_wready      (m_axi_payload_to_retry_buf_wready),
  .wqe_proc_wr_ddr_m_axi_awlock      (m_axi_payload_to_retry_buf_awlock),
  .wqe_proc_wr_ddr_m_axi_bid         (m_axi_payload_to_retry_buf_bid),
  .wqe_proc_wr_ddr_m_axi_bresp       (m_axi_payload_to_retry_buf_bresp),
  .wqe_proc_wr_ddr_m_axi_bvalid      (m_axi_payload_to_retry_buf_bvalid),
  .wqe_proc_wr_ddr_m_axi_bready      (m_axi_payload_to_retry_buf_bready),
  .wqe_proc_wr_ddr_m_axi_arid        (m_axi_payload_to_retry_buf_arid),
  .wqe_proc_wr_ddr_m_axi_araddr      (m_axi_payload_to_retry_buf_araddr),
  .wqe_proc_wr_ddr_m_axi_arlen       (m_axi_payload_to_retry_buf_arlen),
  .wqe_proc_wr_ddr_m_axi_arsize      (m_axi_payload_to_retry_buf_arsize),
  .wqe_proc_wr_ddr_m_axi_arburst     (m_axi_payload_to_retry_buf_arburst),
  .wqe_proc_wr_ddr_m_axi_arcache     (m_axi_payload_to_retry_buf_arcache),
  .wqe_proc_wr_ddr_m_axi_arprot      (m_axi_payload_to_retry_buf_arprot),
  .wqe_proc_wr_ddr_m_axi_arvalid     (m_axi_payload_to_retry_buf_arvalid),
  .wqe_proc_wr_ddr_m_axi_arready     (m_axi_payload_to_retry_buf_arready),
  .wqe_proc_wr_ddr_m_axi_rid         (m_axi_payload_to_retry_buf_rid),
  .wqe_proc_wr_ddr_m_axi_rdata       (m_axi_payload_to_retry_buf_rdata),
  .wqe_proc_wr_ddr_m_axi_rresp       (m_axi_payload_to_retry_buf_rresp),
  .wqe_proc_wr_ddr_m_axi_rlast       (m_axi_payload_to_retry_buf_rlast),
  .wqe_proc_wr_ddr_m_axi_rvalid      (m_axi_payload_to_retry_buf_rvalid),
  .wqe_proc_wr_ddr_m_axi_rready      (m_axi_payload_to_retry_buf_rready),
  .wqe_proc_wr_ddr_m_axi_arlock      (m_axi_payload_to_retry_buf_arlock),

  // Acquire payload data for RDMA send/write/read response packet generation
  .wqe_proc_top_m_axi_awid           (m_axi_pktgen_get_payload_awid),
  .wqe_proc_top_m_axi_awaddr         (m_axi_pktgen_get_payload_awaddr),
  .wqe_proc_top_m_axi_awlen          (m_axi_pktgen_get_payload_awlen),
  .wqe_proc_top_m_axi_awsize         (m_axi_pktgen_get_payload_awsize),
  .wqe_proc_top_m_axi_awburst        (m_axi_pktgen_get_payload_awburst),
  .wqe_proc_top_m_axi_awcache        (m_axi_pktgen_get_payload_awcache),
  .wqe_proc_top_m_axi_awprot         (m_axi_pktgen_get_payload_awprot),
  .wqe_proc_top_m_axi_awvalid        (m_axi_pktgen_get_payload_awvalid),
  .wqe_proc_top_m_axi_awready        (m_axi_pktgen_get_payload_awready),
  .wqe_proc_top_m_axi_wdata          (m_axi_pktgen_get_payload_wdata),
  .wqe_proc_top_m_axi_wstrb          (m_axi_pktgen_get_payload_wstrb),
  .wqe_proc_top_m_axi_wlast          (m_axi_pktgen_get_payload_wlast),
  .wqe_proc_top_m_axi_wvalid         (m_axi_pktgen_get_payload_wvalid),
  .wqe_proc_top_m_axi_wready         (m_axi_pktgen_get_payload_wready),
  .wqe_proc_top_m_axi_awlock         (m_axi_pktgen_get_payload_awlock),
  .wqe_proc_top_m_axi_bid            (m_axi_pktgen_get_payload_bid),
  .wqe_proc_top_m_axi_bresp          (m_axi_pktgen_get_payload_bresp),
  .wqe_proc_top_m_axi_bvalid         (m_axi_pktgen_get_payload_bvalid),
  .wqe_proc_top_m_axi_bready         (m_axi_pktgen_get_payload_bready),
  .wqe_proc_top_m_axi_arid           (m_axi_pktgen_get_payload_arid),
  .wqe_proc_top_m_axi_araddr         (m_axi_pktgen_get_payload_araddr),
  .wqe_proc_top_m_axi_arlen          (m_axi_pktgen_get_payload_arlen),
  .wqe_proc_top_m_axi_arsize         (m_axi_pktgen_get_payload_arsize),
  .wqe_proc_top_m_axi_arburst        (m_axi_pktgen_get_payload_arburst),
  .wqe_proc_top_m_axi_arcache        (m_axi_pktgen_get_payload_arcache),
  .wqe_proc_top_m_axi_arprot         (m_axi_pktgen_get_payload_arprot),
  .wqe_proc_top_m_axi_arvalid        (m_axi_pktgen_get_payload_arvalid),
  .wqe_proc_top_m_axi_arready        (m_axi_pktgen_get_payload_arready),
  .wqe_proc_top_m_axi_rid            (m_axi_pktgen_get_payload_rid),
  .wqe_proc_top_m_axi_rdata          (m_axi_pktgen_get_payload_rdata),
  .wqe_proc_top_m_axi_rresp          (m_axi_pktgen_get_payload_rresp),
  .wqe_proc_top_m_axi_rlast          (m_axi_pktgen_get_payload_rlast),
  .wqe_proc_top_m_axi_rvalid         (m_axi_pktgen_get_payload_rvalid),
  .wqe_proc_top_m_axi_rready         (m_axi_pktgen_get_payload_rready),
  .wqe_proc_top_m_axi_arlock         (m_axi_pktgen_get_payload_arlock),

  // RDMA AXI MM interface used to write completion entries to a completion queue in the DDR
  .resp_hndler_m_axi_awid            (m_axi_write_completion_awid),
  .resp_hndler_m_axi_awaddr          (m_axi_write_completion_awaddr),
  .resp_hndler_m_axi_awlen           (m_axi_write_completion_awlen),
  .resp_hndler_m_axi_awsize          (m_axi_write_completion_awsize),
  .resp_hndler_m_axi_awburst         (m_axi_write_completion_awburst),
  .resp_hndler_m_axi_awcache         (m_axi_write_completion_awcache),
  .resp_hndler_m_axi_awprot          (m_axi_write_completion_awprot),
  .resp_hndler_m_axi_awvalid         (m_axi_write_completion_awvalid),
  .resp_hndler_m_axi_awready         (m_axi_write_completion_awready),
  .resp_hndler_m_axi_wdata           (m_axi_write_completion_wdata),
  .resp_hndler_m_axi_wstrb           (m_axi_write_completion_wstrb),
  .resp_hndler_m_axi_wlast           (m_axi_write_completion_wlast),
  .resp_hndler_m_axi_wvalid          (m_axi_write_completion_wvalid),
  .resp_hndler_m_axi_wready          (m_axi_write_completion_wready),
  .resp_hndler_m_axi_awlock          (m_axi_write_completion_awlock),
  .resp_hndler_m_axi_bid             (m_axi_write_completion_bid),
  .resp_hndler_m_axi_bresp           (m_axi_write_completion_bresp),
  .resp_hndler_m_axi_bvalid          (m_axi_write_completion_bvalid),
  .resp_hndler_m_axi_bready          (m_axi_write_completion_bready),
  .resp_hndler_m_axi_arid            (m_axi_write_completion_arid),
  .resp_hndler_m_axi_araddr          (m_axi_write_completion_araddr),
  .resp_hndler_m_axi_arlen           (m_axi_write_completion_arlen),
  .resp_hndler_m_axi_arsize          (m_axi_write_completion_arsize),
  .resp_hndler_m_axi_arburst         (m_axi_write_completion_arburst),
  .resp_hndler_m_axi_arcache         (m_axi_write_completion_arcache),
  .resp_hndler_m_axi_arprot          (m_axi_write_completion_arprot),
  .resp_hndler_m_axi_arvalid         (m_axi_write_completion_arvalid),
  .resp_hndler_m_axi_arready         (m_axi_write_completion_arready),
  .resp_hndler_m_axi_rid             (m_axi_write_completion_rid),
  .resp_hndler_m_axi_rdata           (m_axi_write_completion_rdata),
  .resp_hndler_m_axi_rresp           (m_axi_write_completion_rresp),
  .resp_hndler_m_axi_rlast           (m_axi_write_completion_rlast),
  .resp_hndler_m_axi_rvalid          (m_axi_write_completion_rvalid),
  .resp_hndler_m_axi_rready          (m_axi_write_completion_rready),
  .resp_hndler_m_axi_arlock          (m_axi_write_completion_arlock),

  // Send WQE completion queue doorbell
  .resp_hndler_o_send_cq_db_cnt_valid(resp_hndler_o_send_cq_db_cnt_valid),
  .resp_hndler_o_send_cq_db_addr     (resp_hndler_o_send_cq_db_addr),
  .resp_hndler_o_send_cq_db_cnt      (resp_hndler_o_send_cq_db_cnt),
  .resp_hndler_i_send_cq_db_rdy      (resp_hndler_i_send_cq_db_rdy),

  // RDMA-Send consumer index doorbell
  .i_qp_rq_cidb_hndshk               (i_qp_rq_cidb_hndshk),
  .i_qp_rq_cidb_wr_addr_hndshk       (i_qp_rq_cidb_wr_addr_hndshk),
  .i_qp_rq_cidb_wr_valid_hndshk      (i_qp_rq_cidb_wr_valid_hndshk),
  .o_qp_rq_cidb_wr_rdy               (o_qp_rq_cidb_wr_rdy),

  // Send WQE producer index doorbell
  .i_qp_sq_pidb_hndshk               (i_qp_sq_pidb_hndshk),
  .i_qp_sq_pidb_wr_addr_hndshk       (i_qp_sq_pidb_wr_addr_hndshk),
  .i_qp_sq_pidb_wr_valid_hndshk      (i_qp_sq_pidb_wr_valid_hndshk),
  .o_qp_sq_pidb_wr_rdy               (o_qp_sq_pidb_wr_rdy),

  // RDMA-Send producer index doorbell
  .rx_pkt_hndler_o_rq_db_data        (rx_pkt_hndler_o_rq_db_data),
  .rx_pkt_hndler_o_rq_db_addr        (rx_pkt_hndler_o_rq_db_addr),
  .rx_pkt_hndler_o_rq_db_data_valid  (rx_pkt_hndler_o_rq_db_data_valid),
  .rx_pkt_hndler_i_rq_db_rdy         (rx_pkt_hndler_i_rq_db_rdy),

  // RDMA RX interface from CMAC RX path in AXIS format
  .roce_cmac_s_axis_tvalid           (s_cmac2rdma_roce_axis_tvalid),
  .roce_cmac_s_axis_tdata            (s_cmac2rdma_roce_axis_tdata),
  .roce_cmac_s_axis_tkeep            (s_cmac2rdma_roce_axis_tkeep),
  .roce_cmac_s_axis_tlast            (s_cmac2rdma_roce_axis_tlast),
  .roce_cmac_s_axis_tuser            (s_cmac2rdma_roce_axis_tuser),

  // Non-RDMA packets from CMAC RX path in AXIS format
  .non_roce_cmac_s_axis_tvalid       (s_cmac2rdma_non_roce_axis_tvalid),
  .non_roce_cmac_s_axis_tdata        (s_cmac2rdma_non_roce_axis_tdata),
  .non_roce_cmac_s_axis_tkeep        (s_cmac2rdma_non_roce_axis_tkeep),
  .non_roce_cmac_s_axis_tlast        (s_cmac2rdma_non_roce_axis_tlast),
  .non_roce_cmac_s_axis_tuser        (s_cmac2rdma_non_roce_axis_tuser),

  // Non-RDMA packets from QDMA TX path in AXIS format bypassing RDMA core
  .non_roce_dma_s_axis_tvalid        (s_qdma2rdma_non_roce_axis_tvalid),
  .non_roce_dma_s_axis_tdata         (s_qdma2rdma_non_roce_axis_tdata),
  .non_roce_dma_s_axis_tkeep         (s_qdma2rdma_non_roce_axis_tkeep),
  .non_roce_dma_s_axis_tlast         (s_qdma2rdma_non_roce_axis_tlast),
  .non_roce_dma_s_axis_tready        (s_qdma2rdma_non_roce_axis_tready),

  // Non-RDMA packets in AXIS format from CMAC RX path bypassing RDMA core to QDMA RX
  .non_roce_dma_m_axis_tvalid        (m_rdma2qdma_non_roce_axis_tvalid),
  .non_roce_dma_m_axis_tdata         (m_rdma2qdma_non_roce_axis_tdata),
  .non_roce_dma_m_axis_tkeep         (m_rdma2qdma_non_roce_axis_tkeep),
  .non_roce_dma_m_axis_tlast         (m_rdma2qdma_non_roce_axis_tlast),
  .non_roce_dma_m_axis_tready        (m_rdma2qdma_non_roce_axis_tready),

  // invalidate or immediate data from roce IETH/IMMDT header
  .ieth_immdt_axis_tvalid            (m_rdma2user_ieth_immdt_axis_tvalid),
  .ieth_immdt_axis_tlast             (m_rdma2user_ieth_immdt_axis_tlast),
  .ieth_immdt_axis_tdata             (m_rdma2user_ieth_immdt_axis_tdata),
  .ieth_immdt_axis_trdy              (m_rdma2user_ieth_immdt_axis_trdy),

  .rnic_intr                         (rnic_intr),
  .stat_rx_pause_req                 (stat_rx_pause_req),
  .ctl_tx_pause_req                  (ctl_tx_pause_req),
  .ctl_tx_resend_pause               (ctl_tx_resend_pause),
  .o_global_dbg_cnt_en               (o_global_dbg_cnt_en),
  .o_global_dbg_cnt_clr              (o_global_dbg_cnt_clr)
);

endmodule : rdma_subsystem
